/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "full_adder.v:1.1-6.10" *)
module full_adder(a, b, cin, sum, cout);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "full_adder.v:2.7-2.8" *)
  input a;
  wire a;
  (* src = "full_adder.v:2.10-2.11" *)
  input b;
  wire b;
  (* src = "full_adder.v:2.13-2.16" *)
  input cin;
  wire cin;
  (* src = "full_adder.v:3.13-3.17" *)
  output cout;
  wire cout;
  (* src = "full_adder.v:3.8-3.11" *)
  output sum;
  wire sum;
  NOR2X1 _3_ (
    .A(a),
    .B(cin),
    .Y(_0_)
  );
  XNOR2X1 _4_ (
    .A(a),
    .B(cin),
    .Y(_1_)
  );
  XNOR2X1 _5_ (
    .A(b),
    .B(_1_),
    .Y(sum)
  );
  AOI21X1 _6_ (
    .A(a),
    .B(cin),
    .C(b),
    .Y(_2_)
  );
  NOR2X1 _7_ (
    .A(_0_),
    .B(_2_),
    .Y(cout)
  );
endmodule
